apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: myapp2
  name: myapp2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: myapp2
    spec:
      containers:
      - image: localhost:5000/microservices_app2:1.0
        name: microservices_app2
        resources: {}
status: {}