apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
     app: myapp2
  name: myapp2-svc
spec:
  ports:
  - name: myapp2
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: myapp2
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}