apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  # annotations:
  #   prometheus.io/port: "8082"
  #   prometheus.io/scrape: "true"
  labels:
     app: myapp2
  name: myapp2-svc
spec:
  ports:
  - name: myapp2
    port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    app: myapp2
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}