version: '3'
services:
  # app1:
  #   build: app1/.
  #   ports:
  #    - "8081:8081"
  # app2:
  #   build: app2/.
  #   ports:
  #    - "8082:8082"
  app3:
    build: app3/.
    ports:
     - "8443:8443"
     - "8083:8083"