apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: test
  creationTimestamp: null
  labels:
    app: myapp1
  name: myapp1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: myapp1
    spec:
      containers:
      - image: localhost:5000/microservices_app1:1.1
        name: microservices-app1
        env:
        - name: APP2
          value: "http://myapp2-svc:8082/bar"
        resources: 
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 3
          periodSeconds: 3
status: {}